[all]
k3s-node-0 ansible_host=192.168.100.1 ansible_user=ubuntu
k3s-node-1 ansible_host=192.168.100.2 ansible_user=ubuntu
k3s-node-2 ansible_host=192.168.100.3 ansible_user=ubuntu
k3s-node-3 ansi0ble_host=192.168.100.4 ansible_user=ubuntu
heimdall ansible_host=192.168.3.4 ansible_user=root
media-server ansible_host=192.168.3.40 ansible_user=root
ubuntu-exporters ansible_host=192.168.3.11 ansible_user=root
ubuntu-monitoring ansible_host=192.168.3.10 ansible_user=root
dns-01 ansible_host=192.168.3.20 ansible_user=root
certificate-authority ansible_host=192.168.3.6 ansible_user=ubuntu

[monitoring]
ubuntu-monitoring ansible_host=192.168.3.10 ansible_user=root
ubuntu-exporters ansible_host=192.168.3.11 ansible_user=root