---

- name: Install docker dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3-pip
    - python3-setuptools
    

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: install docker
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
- name: Add user to docker group
  become: true
  user:
    name: ubuntu
    groups: 
     - docker
    append: true
- name: Enable & Start Docker service
  become: true
  service:
    name: docker
    enabled: true
    state: started
- name: Install pip components
  pip:
    executable: pip3
    name:
      - docker
      - docker-compose
      - virtualenv